# Generated by Django 5.1 on 2024-08-29 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_desc',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
